const $=s=>document.querySelector(s), money=n=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(Number(n||0));
const KEY='bo_consolidado_v9';
function seedUnits(){const defs=[['BW','Bota Walker',30,400,4000],['SR','Silla de ruedas',15,700,7000],['MAR','Muleta de aluminio reforzada mediana',10,400,4000],['AA','Andador aluminio',6,400,4000],['BRC','Bastón reforzado canadiense',5,400,4000],['BAR','Bastón de aluminio regulable en altura',5,400,4000],['BT','Bastón trípode',5,400,4000],['CF','Collar Filadelfia',3,400,4000],['CDS','Cabestrillo con soporte de brazo doble sujeción',8,400,4000],['CO','Cama ortopédica',7,700,7000],['IP','Inodoro portátil',4,400,4000],['CH','Chatas',3,400,4000],['PA','Papagallos',2,400,4000],['IT','Inmovilizador de tobillo',5,400,4000],['IR','Inmovilizador de rodilla',5,400,4000],['IRB','Inmovilizador de rodilla con ballena',5,400,4000],['BD','Banco para duchas',5,400,4000],['OT','Otros',5,400,4000]];let id=1,a=[];defs.forEach(([p,n,q,price,g])=>{for(let i=1;i<=q;i++)a.push({id:id++,code:`${p}-${String(i).padStart(3,'0')}`,name:n,price,guarantee:g,cost:0,photo:'',status:'Disponible',where:'Depósito'})});return a}
let data=JSON.parse(localStorage.getItem(KEY)||'null')||{units:seedUnits(),rentals:[],receiptSeq:0};let draft={},view='home';
function save(){localStorage.setItem(KEY,JSON.stringify(data))} function toast(t){let x=$('#toast');x.textContent=t;x.style.display='block';setTimeout(()=>x.style.display='none',2500)} function go(v){view=v;render()} function unit(id){return data.units.find(x=>x.id==id)} function rental(id){return data.rentals.find(x=>x.id==id)} function today(){return new Date().toISOString().slice(0,10)} function addDays(d,n){let x=new Date(d+'T12:00:00');x.setDate(x.getDate()+Number(n));return x.toISOString().slice(0,10)} function now(){return new Date().toLocaleString('es-AR')} function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function ledger(r){r.charges=r.charges||[];r.payments=r.payments||[];r.receipts=r.receipts||[];return r}
function sum(a,concept){return (a||[]).filter(x=>!concept||x.concept===concept).reduce((s,x)=>s+Number(x.amount||0),0)}
function rentalCharges(r){return sum(ledger(r).charges,'Alquiler')} function rentPayments(r){return sum(r.payments,'Alquiler')} function guaranteePaid(r){return sum(r.payments,'Garantía')-sum(r.charges,'Garantía devuelta')-sum(r.charges,'Garantía aplicada')-sum(r.charges,'Garantía donada')} function balanceRent(r){return Math.max(0,rentalCharges(r)-rentPayments(r)-sum(r.charges,'Garantía aplicada'))} function totalPayments(r){return sum(r.payments)}
function wa(phone,msg){if(window.Android&&Android.openWhatsApp)Android.openWhatsApp(String(phone||''),msg);else window.open('https://wa.me/?text='+encodeURIComponent(msg),'_blank')}
function render(){const m=$('#main');if(view==='home')m.innerHTML=home();if(view==='rentals')m.innerHTML=rentals();if(view==='stock')m.innerHTML=stock();if(view==='returns')m.innerHTML=returns();if(view==='reports')m.innerHTML=reports()}
function home(){let a=data.rentals.filter(x=>x.status==='Activo').length,p=data.rentals.filter(x=>x.status==='Pendiente aceptación').length;return `<h2>Inicio</h2><div class=sub>Gestión del Banco Ortopédico</div><div class=grid><button class=card onclick="newRental(1)"><div class=ico>♿</div><b>Nuevo alquiler</b><span class=mut>Proceso en 3 pasos</span></button><button class=card onclick="go('rentals')"><div class=ico>📋</div><b>Alquileres</b><span class=mut>${a} activos · ${p} pendientes</span></button><button class=card onclick="go('stock')"><div class=ico>📦</div><b>Inventario / Stock</b><span class=mut>${data.units.length} unidades codificadas</span></button><button class=card onclick="go('returns')"><div class=ico>↩️</div><b>Devolución / Cierre</b><span class=mut>Garantía, saldo y estado</span></button><button class=card onclick="go('reports')"><div class=ico>📊</div><b>Reportes</b><span class=mut>Recaudación y recuperación</span></button></div>`}
function newRental(step){view='wizard';$('#main').innerHTML=`<div class=row><button class="btn light" onclick="go('home')">← Inicio</button><div style="flex:2"><b>Nuevo alquiler</b><div class=mut>Paso ${step} de 3</div></div></div><div class=steps><i class=on></i><i class="${step>1?'on':''}"></i><i class="${step>2?'on':''}"></i></div>`+(step===1?step1():step===2?step2():step3());if(step===2)calc2()}
function step1(){return `<h2>1. Cliente</h2><label>Nombre y apellido</label><input id=n value="${esc(draft.name||'')}"><label>DNI</label><input id=dni value="${esc(draft.dni||'')}"><label>WhatsApp</label><input id=wa value="${esc(draft.wa||'')}"><label>Dirección</label><input id=addr value="${esc(draft.addr||'')}"><br><button class="btn blue full" onclick=save1()>Siguiente →</button>`}
function save1(){draft.name=$('#n').value.trim();draft.dni=$('#dni').value.trim();draft.wa=$('#wa').value.trim();draft.addr=$('#addr').value.trim();if(!draft.name||!draft.wa){toast('Completá nombre y WhatsApp');return}newRental(2)}
function step2(){let o=data.units.filter(x=>x.status==='Disponible').map(x=>`<option value=${x.id}>${x.code} · ${x.name} · ${money(x.price)}/día</option>`).join('');return `<h2>2. Elemento y período</h2><div class=sub>Mínimo 1 día · máximo 90 días.</div><label>Elemento</label><select id=u onchange=calc2()>${o}</select><label>Fecha de inicio</label><input id=start type=date value="${draft.start||today()}" onchange=calc2()><label>Días</label><input id=rdays type=number min=1 max=90 value="${draft.days||1}" oninput="calc2(true)"><label>Vencimiento</label><input id=end readonly><div class=money id=c2></div><div class=row><button class="btn light" onclick="newRental(1)">← Atrás</button><button class="btn blue" onclick=save2()>Siguiente →</button></div>`}
function calc2(blank){let d=$('#rdays'),u=unit(Number($('#u').value));if(!d||!u)return;if(d.value===''&&blank){$('#end').value='';$('#c2').innerHTML='';return}let n=Number(d.value||1);$('#end').value=addDays($('#start').value,n);$('#c2').innerHTML=`<div><span>Valor diario</span><b>${money(u.price)}</b></div><div><span>Garantía</span><b>${money(u.guarantee)}</b></div><div><span>Alquiler</span><b>${money(u.price*n)}</b></div>`}
function save2(){let n=Number($('#rdays').value);if(!Number.isInteger(n)||n<1||n>90){toast('Ingresá entre 1 y 90 días');return}let u=unit(Number($('#u').value));draft.uid=u.id;draft.start=$('#start').value;draft.days=n;draft.end=addDays(draft.start,n);newRental(3)}
function step3(){let u=unit(draft.uid),rent=u.price*draft.days,total=rent+u.guarantee;return `<h2>3. Reporte inicial</h2><div class=money><div><span>Cliente</span><b>${esc(draft.name)}</b></div><div><span>Elemento</span><b>${u.code}</b></div><div><span>${draft.days} día(s) × ${money(u.price)}</span><b>${money(rent)}</b></div><div><span>Garantía</span><b>${money(u.guarantee)}</b></div><div class=total><span>Total informado</span><b>${money(total)}</b></div></div><div class=contract><b>📲 Primero se envía el reporte</b><p class=mut>Luego el encargado verifica el pago y genera el recibo.</p></div><div class=row><button class="btn light" onclick="newRental(2)">← Atrás</button><button class="btn yellow" onclick=createRental()>Enviar por WhatsApp</button></div>`}
function createRental(){let u=unit(draft.uid),rent=u.price*draft.days,id=Date.now(),r={id,number:'ALQ-'+String(data.rentals.length+1).padStart(5,'0'),client:draft.name,dni:draft.dni,wa:draft.wa,addr:draft.addr,uid:u.id,start:draft.start,end:draft.end,days:draft.days,rate:u.price,guaranteeRequired:u.guarantee,status:'Pendiente aceptación',accepted:false,charges:[{date:today(),concept:'Alquiler',amount:rent},{date:today(),concept:'Garantía requerida',amount:u.guarantee}],payments:[],receipts:[],extensions:[]};data.rentals.unshift(r);save();wa(r.wa,`Banco Ortopédico - Reporte inicial\n${r.number}\nCliente: ${r.client}\nElemento: ${u.name} ${u.code}\nDesde: ${r.start} hasta: ${r.end}\nDías: ${r.days}\nAlquiler: ${money(rent)}\nGarantía: ${money(u.guarantee)}\nTotal informado: ${money(rent+u.guarantee)}\nPor favor revise y confirme el alquiler.`);view='rentals';render();toast('Reporte inicial enviado/preparado')}
function rentalCard(r){let u=unit(r.uid),bal=balanceRent(r),gp=Math.max(0,guaranteePaid(r));return `<div class=item><div class=itemtop><div><b>${esc(r.client)}</b><div class=mut>${r.number} · ${u.code} · vence ${r.end}</div></div><span class="badge ${r.status==='Activo'?'active':'pending'}">${r.status}</span></div><div class=money><div><span>Alquiler pendiente</span><b>${money(bal)}</b></div><div><span>Garantía depositada</span><b>${money(gp)}</b></div></div><button class="btn blue full" onclick="paymentScreen(${r.id})">💵 Registrar / confirmar pago</button>${!r.accepted?`<button class="btn yellow full" style="margin-top:8px" onclick="acceptRental(${r.id})">✅ Registrar aceptación</button>`:''}${r.accepted&&r.status!=='Cerrado'?`<button class="btn light full" style="margin-top:8px" onclick="expiry(${r.id})">🔔 Vencimiento / extensión</button>`:''}<button class="btn light full" style="margin-top:8px" onclick="historyScreen(${r.id})">🧾 Historial / recibos</button></div>`}
function rentals(){return `<h2>Alquileres</h2><button class="btn blue full" onclick="newRental(1)">＋ Nuevo alquiler</button>`+(data.rentals.length?data.rentals.map(rentalCard).join(''):`<div class=panel>Sin alquileres.</div>`)}
function acceptRental(id){let r=rental(id),u=unit(r.uid);r.accepted=true;r.acceptedAt=now();r.status='Activo';u.status='Alquilado';u.where=r.client;save();render();toast('Aceptación registrada · stock Alquilado')}
function paymentScreen(id){let r=rental(id),rentDue=balanceRent(r),gDue=Math.max(0,r.guaranteeRequired-Math.max(0,guaranteePaid(r)));$('#main').innerHTML=`<h2>Confirmar pago</h2><div class=panel><b>${esc(r.client)}</b><div class=mut>${r.number}</div></div><div class=money><div><span>Alquiler pendiente</span><b>${money(rentDue)}</b></div><div><span>Garantía pendiente</span><b>${money(gDue)}</b></div></div><label>Pago aplicado a alquiler</label><input id=pr type=number min=0 value="${rentDue}"><label>Pago aplicado a garantía</label><input id=pg type=number min=0 value="${gDue}"><label>Forma de pago</label><select id=pm><option>Efectivo</option><option>Transferencia</option></select><div class=contract><b>Verificación del encargado</b><p class=mut>El recibo se genera únicamente después de verificar el dinero.</p></div><button class="btn yellow full" onclick="confirmPayment(${id})">Confirmar pago y generar recibo</button><br><br><button class="btn light full" onclick="go('rentals')">Cancelar</button>`}
function confirmPayment(id){let r=rental(id),a=Math.max(0,Number($('#pr').value)||0),g=Math.max(0,Number($('#pg').value)||0),method=$('#pm').value;if(a+g<=0){toast('Ingresá un importe recibido');return}let dt=now();if(a)r.payments.push({date:today(),dateTime:dt,concept:'Alquiler',amount:a,method});if(g)r.payments.push({date:today(),dateTime:dt,concept:'Garantía',amount:g,method});let no=++data.receiptSeq,rec={no,dateTime:dt,method,rent:a,guarantee:g,total:a+g,annulled:false};r.receipts.push(rec);save();receiptScreen(id,no)}
function receiptScreen(id,no){let r=rental(id),rec=r.receipts.find(x=>x.no===no);$('#main').innerHTML=`<h2>RECIBO N.º ${String(no).padStart(6,'0')}</h2><div class=money><div><span>Cliente</span><b>${esc(r.client)}</b></div><div><span>Alquiler</span><b>${money(rec.rent)}</b></div><div><span>Garantía</span><b>${money(rec.guarantee)}</b></div><div><span>Forma</span><b>${rec.method}</b></div><div class=total><span>Total recibido</span><b>${money(rec.total)}</b></div><div><span>Saldo alquiler</span><b>${money(balanceRent(r))}</b></div></div><button class="btn yellow full" onclick="sendReceipt(${id},${no})">📲 Enviar recibo por WhatsApp</button><br><br><button class="btn blue full" onclick="go('rentals')">Volver</button>`}
function sendReceipt(id,no){let r=rental(id),x=r.receipts.find(z=>z.no===no);wa(r.wa,`Banco Ortopédico - RECIBO N.º ${String(no).padStart(6,'0')}\n${r.number}\nCliente: ${r.client}\nAlquiler: ${money(x.rent)}\nGarantía: ${money(x.guarantee)}\nTotal recibido: ${money(x.total)}\nForma: ${x.method}\nSaldo alquiler: ${money(balanceRent(r))}\nFecha: ${x.dateTime}`)}
function historyScreen(id){let r=rental(id);$('#main').innerHTML=`<h2>Historial ${r.number}</h2><div class=panel><b>${esc(r.client)}</b><p class=mut>Saldo alquiler: ${money(balanceRent(r))} · Garantía depositada: ${money(Math.max(0,guaranteePaid(r)))}</p></div>${r.receipts.length?r.receipts.map(x=>`<div class=item><b>Recibo ${String(x.no).padStart(6,'0')}</b><div class=mut>${x.dateTime} · ${x.method}</div><div>Total ${money(x.total)} (Alq. ${money(x.rent)} · Garantía ${money(x.guarantee)})</div><button class="btn light full" onclick="sendReceipt(${id},${x.no})">Enviar por WhatsApp</button></div>`).join(''):'<div class=panel>Sin recibos.</div>'}<button class="btn light full" onclick="go('rentals')">Volver</button>`}
function expiry(id){let r=rental(id);$('#main').innerHTML=`<h2>Vencimiento / Extensión</h2><div class=money><div><span>Vence</span><b>${r.end}</b></div><div><span>Saldo alquiler</span><b>${money(balanceRent(r))}</b></div></div><button class="btn yellow full" onclick="sendExpiry(${id})">📲 Enviar aviso por WhatsApp</button><label>Días de extensión</label><input id=ext type=number min=1 max=90 value=1><button class="btn blue full" onclick="extend(${id})">Agregar extensión</button><br><br><button class="btn light full" onclick="markReturn(${id})">Coordinar devolución</button>`}
function sendExpiry(id){let r=rental(id),u=unit(r.uid);wa(r.wa,`Banco Ortopédico - Aviso de vencimiento\n${r.number}\n${u.name} ${u.code}\nVencimiento: ${r.end}\nSaldo pendiente de alquiler: ${money(balanceRent(r))}\nPuede solicitar extensión o coordinar devolución.`)}
function extend(id){let r=rental(id),d=Number($('#ext').value);if(!Number.isInteger(d)||d<1||d>90){toast('Ingresá entre 1 y 90 días');return}let amount=d*r.rate;r.charges.push({date:today(),concept:'Alquiler',amount,note:`Extensión ${d} días`});r.extensions.push({date:today(),days:d,amount,oldEnd:r.end,newEnd:addDays(r.end,d)});r.end=addDays(r.end,d);r.days+=d;save();toast('Extensión cargada como nuevo cargo');paymentScreen(id)}
function markReturn(id){rental(id).status='Pendiente devolución';save();go('returns')}
function stock(){return `<h2>Inventario / Stock</h2><div class=panel><b>${data.units.length} unidades</b><div class=mut>Precio, garantía y costo de adquisición son editables por código.</div></div>`+data.units.map(u=>`<div class=item><div class=itemtop><div><b>${u.code} · ${u.name}</b><div class=mut>${u.where}</div></div><span class="badge ${u.status==='Disponible'?'active':'pending'}">${u.status}</span></div><div class=mut>Valor ${money(u.price)}/día · Garantía ${money(u.guarantee)} · Costo ${money(u.cost)}</div><button class="btn light full" onclick="editStock(${u.id})">✏ Editar</button></div>`).join('')}
function editStock(id){let u=unit(id);$('#main').innerHTML=`<h2>Editar ${u.code}</h2><label>Descripción</label><input id=sn value="${esc(u.name)}"><label>Valor diario</label><input id=sp type=number value=${u.price}><label>Garantía</label><input id=sg type=number value=${u.guarantee}><label>Costo de adquisición</label><input id=sc type=number value=${u.cost||0}><button class="btn blue full" onclick="saveStock(${id})">Guardar</button><br><br><button class="btn light full" onclick="go('stock')">Cancelar</button>`}
function saveStock(id){let u=unit(id);u.name=$('#sn').value;u.price=Number($('#sp').value)||0;u.guarantee=Number($('#sg').value)||0;u.cost=Number($('#sc').value)||0;save();go('stock');toast('Ficha actualizada')}
function returns(){let rs=data.rentals.filter(r=>r.accepted&&r.status!=='Cerrado'&&r.status!=='Cerrado con saldo pendiente');return `<h2>Devolución / Cierre</h2>`+(rs.length?rs.map(r=>`<div class=item><b>${esc(r.client)}</b><div class=mut>${r.number} · ${unit(r.uid).code}</div><button class="btn blue full" onclick="closeScreen(${r.id})">Abrir cierre</button></div>`).join(''):'<div class=panel>No hay devoluciones para cerrar.</div>')}
function closeScreen(id){let r=rental(id),gp=Math.max(0,guaranteePaid(r)),bal=balanceRent(r);$('#main').innerHTML=`<h2>Cierre</h2><div class=money><div><span>Saldo de alquiler</span><b>${money(bal)}</b></div><div><span>Garantía depositada</span><b>${money(gp)}</b></div></div><label>Aplicar garantía a saldo</label><input id=ga type=number min=0 max="${Math.min(gp,bal)}" value=0><label>Donar garantía</label><input id=gd type=number min=0 max="${gp}" value=0><div class=mut>El resto de la garantía se considera a devolver.</div><label>Estado del elemento</label><select id=cond><option>Buen estado</option><option>Requiere mantenimiento</option><option>Dañado</option></select><button class="btn yellow full" onclick="prepareClose(${id})">Generar reporte de cierre</button><br><br><button class="btn light full" onclick="go('returns')">Cancelar</button>`}
function prepareClose(id){let r=rental(id),gp=Math.max(0,guaranteePaid(r)),bal=balanceRent(r),apply=Math.min(Math.max(0,Number($('#ga').value)||0),gp,bal),don=Math.max(0,Number($('#gd').value)||0);if(apply+don>gp){toast('Aplicación + donación supera la garantía');return}let refund=gp-apply-don,finalBal=Math.max(0,bal-apply),cond=$('#cond').value;r.closeDraft={date:today(),apply,don,refund,finalBal,condition:cond};save();$('#main').innerHTML=`<h2>Reporte final</h2><div class=money><div><span>Saldo antes de garantía</span><b>${money(bal)}</b></div><div><span>Garantía aplicada</span><b>${money(apply)}</b></div><div><span>Garantía donada</span><b>${money(don)}</b></div><div><span>Garantía a devolver</span><b>${money(refund)}</b></div><div class=total><span>Saldo real pendiente</span><b>${money(finalBal)}</b></div></div><button class="btn yellow full" onclick="sendClose(${id})">📲 Enviar reporte por WhatsApp</button><br><br><button class="btn blue full" onclick="acceptClose(${id})">✅ Registrar ACEPTAR CIERRE</button>`}
function sendClose(id){let r=rental(id),c=r.closeDraft,u=unit(r.uid);wa(r.wa,`Banco Ortopédico - Reporte de cierre\n${r.number}\nCliente: ${r.client}\nElemento: ${u.name} ${u.code}\nGarantía aplicada: ${money(c.apply)}\nGarantía donada: ${money(c.don)}\nGarantía a devolver: ${money(c.refund)}\nSaldo pendiente: ${money(c.finalBal)}\nEstado: ${c.condition}\nPor favor revise y confirme el cierre.`)}
function acceptClose(id){let r=rental(id),c=r.closeDraft,u=unit(r.uid);if(c.apply)r.charges.push({date:today(),concept:'Garantía aplicada',amount:c.apply});if(c.don)r.charges.push({date:today(),concept:'Garantía donada',amount:c.don});if(c.refund)r.charges.push({date:today(),concept:'Garantía devuelta',amount:c.refund});c.acceptedAt=now();r.close=c;r.status=c.finalBal>0?'Cerrado con saldo pendiente':'Cerrado';u.status=c.condition==='Buen estado'?'Disponible':'Mantenimiento';u.where=u.status==='Disponible'?'Depósito':'Mantenimiento';save();$('#main').innerHTML=`<div class=okbox><div class=big>✅</div><h2>${r.status}</h2><p>El elemento quedó ${u.status}. Saldo: ${money(c.finalBal)}</p>${c.finalBal>0?`<button class="btn yellow full" onclick="paymentScreen(${id})">Registrar pago pendiente</button>`:''}<br><button class="btn blue full" onclick="go('home')">Inicio</button></div>`}
function reportRows(from,to){let rows=[];data.rentals.forEach(r=>{let u=unit(r.uid),ps=(r.payments||[]).filter(p=>p.concept==='Alquiler'&&p.date>=from&&p.date<=to),cash=sum(ps.filter(p=>p.method==='Efectivo')),tr=sum(ps.filter(p=>p.method==='Transferencia')),rec=cash+tr;if(rec>0||((r.start>=from&&r.start<=to)||(r.end>=from&&r.end<=to)))rows.push({name:u.name,code:u.code,days:r.days,revenue:rec,cash,transfer:tr,cost:u.cost||0,totalRevenue:rentPayments(r),rate:u.price})});return rows}
function reports(){let first=new Date();first.setDate(1);let f=first.toISOString().slice(0,10);return `<h2>Reportes</h2><label>Desde</label><input id=rf type=date value="${f}"><label>Hasta</label><input id=rt type=date value="${today()}"><button class="btn blue full" onclick=runReport()>Generar reporte</button><div id=rout style="margin-top:12px"></div>`}
function runReport(){let f=$('#rf').value,t=$('#rt').value,rows=reportRows(f,t),tot=rows.reduce((a,x)=>({days:a.days+x.days,rev:a.rev+x.revenue,cash:a.cash+x.cash,tr:a.tr+x.transfer}),{days:0,rev:0,cash:0,tr:0});$('#rout').innerHTML=`<div class=money><div><span>Recaudación</span><b>${money(tot.rev)}</b></div><div><span>Efectivo</span><b>${money(tot.cash)}</b></div><div><span>Transferencia</span><b>${money(tot.tr)}</b></div></div><div class=tablewrap><table><thead><tr><th>Elemento</th><th>Cód.</th><th>Días</th><th>Recaudación</th><th>Efectivo</th><th>Transferencia</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.name)}</td><td>${x.code}</td><td>${x.days}</td><td>${money(x.revenue)}</td><td>${money(x.cash)}</td><td>${money(x.transfer)}</td></tr>`).join('')}</tbody></table></div><h3>Recuperación de costos</h3>${rows.map(x=>`<div class=item><b>${x.code} · ${esc(x.name)}</b><div class=mut>Costo ${money(x.cost)} · Recaudado histórico ${money(x.totalRevenue)}</div><div>${x.cost>0?`Recuperación: ${Math.round(x.totalRevenue/x.cost*100)}% · Días teóricos al precio actual: ${Math.ceil(x.cost/x.rate)}`:'Cargá el costo de adquisición para calcular recuperación.'}</div></div>`).join('')}<div class=row><button class="btn yellow" onclick="downloadExcel('${f}','${t}')">📊 Descargar Excel</button><button class="btn light" onclick=printReport()>🖨️ Imprimir / PDF</button></div>`}
function downloadExcel(f,t){let rows=reportRows(f,t),lines=[['Elemento','Código','Días alquilado','Recaudación','Efectivo','Transferencia'],...rows.map(x=>[x.name,x.code,x.days,x.revenue,x.cash,x.transfer])];let csv='\ufeff'+lines.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(';')).join('\n');if(window.Android&&Android.saveTextFile)Android.saveTextFile(`Reporte_Banco_Ortopedico_${f}_${t}.csv`,csv,'text/csv');else toast('Descarga disponible en la app Android')}
function printReport(){if(window.Android&&Android.printPage)Android.printPage();else window.print()}
render();
